<a href="https://colab.research.google.com/github/UNKOkiss/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลาย ๆ ตัวไว้ด้วยกันอย่างเป็นระเบียบ

## ```list()```
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ

In [22]:
list_a = [1,2,3,4,5,6] # [ ] square brackets

In [23]:
list_a

[1, 2, 3, 4, 5, 6]

In [24]:
list_b = ['ab',2,3.14,list_a] # list สามารภเก็บตัวแปร string, int, float และ list ได้

In [25]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [26]:
list_a[3] # เริ่มนับจาก 0,1,2,3,.... แล้วลำดับที่ 3 คือเลข 4

4

In [27]:
list_b[3] # ลำดับที่ 3 ของ list_b คือ list_a

[1, 2, 3, 4, 5, 6]

In [28]:
list_b[3][4] # ชี้เลขใน list_a ที่อยู่ใน list_b

5

In [29]:
list_a[6] # ถ้าลำดับเกินจะเกิด error

IndexError: ignored

In [ ]:
list_a[-1] # index -1 คือตัวสุดท้ายของ list

In [ ]:
list_a[-4] # ตัวที่ 3 นับจากตัวสุดท้าย

### การสร้าง `list()`

In [ ]:
list_x1 = [] # แบบที่ 1
list_x2 = list() # แบบที่ 2

In [ ]:
print(list_x1)
print(list_x2)

### เพื่อสมาชิกเข้าไปใน list ด้วย `append()`

In [ ]:
list_x1.append(2) # เพิ่มเลข 2 เข้าใน list

In [ ]:
list_x1

In [ ]:
list_x1.append(4) # เพิ่มเลข 4 เข้าไปใน list
print(list_x1)

In [ ]:
list_x1[0]

In [ ]:
list_x1[-1]

In [ ]:
list_x2

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

### ลบสมาชิกจาก list

In [ ]:
list_x1.append('ha')

In [ ]:
list_x1 # มี ha เข้ามาใน list แล้วเราอยากลบออก ลบยังไง?

In [ ]:
list_x1.pop() # ใช้คำสั่ง pop มันจะลบตัวสุดท้ายของ list ออก

In [ ]:
list_x1

In [ ]:
list_x1.pop() # ใช้คำสั่ง pop อีกครั้งมันจะลบตัวสุดท้ายออก ทำให้ ha ha หายหมด
print(list_x1)

### `len()` ตรวจสอบจำนวนสมาชิกของ list

In [ ]:
print(list_b)
print(len(list_b)) # นับจำนวนสมาชิกใน list_b

In [ ]:
len(list_a)

### String is list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10] # ตำแหน่งที่ 10 คือช่องว่างพอดี (นับจาก 0,1,2,...)

In [ ]:
len(st_stat)

### List Slicing `:`

`list [จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]`

`list [จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง):step]`

In [ ]:
list_a

In [ ]:
list_a[2]

#### `:` colon

In [ ]:
list_a[-3:] # : colon คือ list สามตัวสุดท้ายของ list มา

In [ ]:
list_a[1:4] # เริ่มเอาตัวที่ 1 ไปถึงตัวที่ 3 (ตัวที่ 4 ไม่นับเพราะโปร่ง)

In [ ]:
list_a[:]

#### step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:]

In [ ]:
list_c[:10:2] # step = 2 คือนับทีละสอง

In [ ]:
list_c[::-1] # step = -1 คือเริ่มจากด้านหลังทีละหนึ่ง

### `range()`

In [ ]:
range(21) # รู้ว่าเริ่มที่ 0 ถึง 20

In [ ]:
a = list(range(21)) # สั่งให้มัน list ออกมา

In [ ]:
a

In [ ]:
list(range(1,21)) # สามารถกำเนิดได้ว่าให้ list ตั้งแต่ไหนถึงไหน

## HW2

HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [30]:
# 01:02:03

a = (1*60*60) + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


In [31]:
# 12:30:15

a = (12*60*60) + (30*60) +15
print(f'12:30:15 แปลงเป็นวินาที ได้ {a} วินาที')

12:30:15 แปลงเป็นวินาที ได้ 45015 วินาที


In [32]:
# 13:41:07

b = (13*60*60) + (41*60) + 7
print(f'13:41:07 แปลงเป็นวินาที ได้ {b} วินาที')

13:41:07 แปลงเป็นวินาที ได้ 49267 วินาที


In [33]:
# 09:11:50

c = (9*60*60) + (11*60) + 50
print(f'09:11:50 แปลงเป็นวินาที ได้ {c} วินาที')

09:11:50 แปลงเป็นวินาที ได้ 33110 วินาที


In [34]:
# 21:30:15

d = (21*60*60) + (30*60) + 15
print(f'21:30:15 แปลงเป็นวินาที ได้ {d} วินาที')

21:30:15 แปลงเป็นวินาที ได้ 77415 วินาที


In [35]:
# 03:10:15

e = (3*60*60) + (10*60) + 15
print(f'03:10:15 แปลงเป็นวินาที ได้ {e} วินาที')

03:10:15 แปลงเป็นวินาที ได้ 11415 วินาที


## Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

### การชี้ สมาชิกใน Dictionary

In [36]:
dict_a = {1 : 'Happy' , 'N' : 'New' , '2022' : 'Year'} # { } เรียกว่า culry brackets , 1 จะชี้ไปที่คำว่า happy , N จะชี้ไปที่คำว่า New , 2022 จะชี้ไปที่คำว่า Year

In [37]:
dict_a[1]

'Happy'

In [38]:
dict_a['N']

'New'

In [39]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [40]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [41]:
dict_a[7] = 3.14

In [42]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [43]:
dict_a['N'] = 'NNNEEEEWWW'

In [44]:
dict_a # ถ้าชี้ซ้ำ มันจะไปอัพเดตทับค่าเดิมเป็นค่าใหม่

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNEEEEWWW'}

## Numpy Array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้ พิกัด (2 มิติ ก็มองเป็น Matrix)

In [45]:
import numpy

### 1D array

In [72]:
list_A = [1,2,3,4,5]

In [73]:
arr_a = numpy.array(list_A)

In [74]:
arr_a

array([1, 2, 3, 4, 5])

In [75]:
list_A

[1, 2, 3, 4, 5]

In [76]:
arr_a[0]

1

In [77]:
list_A[0]

1

In [78]:
5*arr_a # Matrix (scalar multiplcation) 5 คูณกระจายเข้าในเมทริกซ์

array([ 5, 10, 15, 20, 25])

In [79]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [80]:
arr_b = numpy.array([10,20,30,40,50])

In [81]:
print(arr_a)

[1 2 3 4 5]


In [82]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

### 2D array

In [87]:
import numpy as np # นำเข้า numpy พร้อมเปลี่ยนชื่อให้สั้นลงเป็นคำว่า np

In [88]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [89]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr2_z.shape

(2, 3)

### np.zeros()

In [61]:
arr2_3_5_0 = np.zeros((3,5))

In [62]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
arr2_3_5_0[1,2] = 9

In [64]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
arr2_3_5_0[1,2]

9.0

In [66]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### np.ones()

In [67]:
arr2_4_5_1 = np.ones((4,5))

In [68]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
arr2_4_5_200 = 200*np.ones((4,5))

In [70]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operations

#### การบวก ลบ matrix $M \pm N$ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [71]:
arr2_4_5_200 + arr2_3_5_0 # การบวก ลบ matrix shape ต้องเท่ากัน

ValueError: ignored

In [ ]:
arr2_4_5_200 + arr2_4_5_1

#### การคูณ matrix

- $aM$ scalar คูณ Matrix (คูณกระจายเข้าไปทุกตัวของ Matrix)
- $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)

$aM$

In [ ]:
5*arr_a # Matrix (scalar multiplication)

$M\times N$ (dot product)
- (m,n) $\times$ (n,o) = (m,o) (Shape)

In [ ]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [ ]:
mat_a

In [ ]:
mat_b

In [ ]:
mat_c

axc, bxc

In [ ]:
np.dot(mat_a,mat_c)

In [ ]:
np.dot(mat_b,mat_c)

cxa, cxb

In [ ]:
np.dot(mat_c,mat_a)

In [ ]:
np.dot(mat_c,mat_b)

In [ ]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

In [ ]:
mat_a * mat_b # คูณตัวตำแหน่งเดียวกัน ไม่ใช่คุณสมบัติเมทริกซ์

### Matrix Slicing

In [ ]:
mat_X[:2,:2]

HW 3

1. สร้าง array ที่เป็นรูป ต้น Chrismas
2. slicing เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [ ]:
HW3 = np.ones((25,15))
HW3

In [ ]:
HW3[1:5,7] = 77
HW3[2:6,6] = 77
HW3[2:6,8] = 77
HW3[2,5] = 77
HW3[2,9] = 77
HW3[5:24,7] = 9
HW3[6:24,6] = 9
HW3[6:24,8] = 9
HW3[7:20,5] = 9
HW3[7:20,9] = 9
HW3[8:19,4] = 9
HW3[8:19,10] = 9
HW3[9:11,3] = 9
HW3[9:11,11] = 9
HW3[10:11,2] = 9
HW3[10:11,12] = 9
HW3[12:15,3] = 9
HW3[12:15,11] = 9
HW3[13:15,2] = 9
HW3[13:15,12] = 9
HW3[14:15,1] = 9
HW3[14:15,13] = 9
HW3[16:20,3] = 9
HW3[16:20,11]= 9
HW3[17:20,2] = 9
HW3[17:20,12] = 9
HW3[18:20,1] = 9
HW3[18:20,13] = 9
HW3[19] = 9
HW3[5:6,7] = 99
HW3[6:7,6] = 99
HW3[6:7,8] = 99
HW3[7:8,5] = 99
HW3[7:8,9] = 99
HW3[8:9,4] = 99
HW3[8:9,10] = 99
HW3[9:10,3] = 99
HW3[9:10,11] = 99
HW3[10:11,2] = 99
HW3[10:11,12] = 99
HW3[10:11,3] = 99
HW3[10:11,4] = 99
HW3[10:11,11] = 99
HW3[10:11,10] = 99
HW3[11:12,4] = 99
HW3[11:12,10] = 99
HW3[12:13,3] = 99
HW3[13:15,2] = 99
HW3[14:15,1] = 99
HW3[12:13,11] = 99
HW3[13:15,12] = 99
HW3[14:15,13] = 99
HW3[14:15,3] = 99
HW3[14:15,11] = 99
HW3[14:16,4] = 99
HW3[14:16,10] = 99
HW3[16:17,3] = 99
HW3[17:18,2] = 99
HW3[18:20,1] = 99
HW3[19:20,0] = 99
HW3[16:17,11] = 99
HW3[17:18,12] = 99
HW3[18:20,13] = 99
HW3[19:20,2] = 99
HW3[19:20,3] = 99
HW3[19:20,4] = 99
HW3[19:20,9] = 99
HW3[19:20,10] = 99
HW3[19:20,11] = 99
HW3[19:20,12] = 99
HW3[19:20,13] = 99
HW3[20:25,6] = 99
HW3[20:25,8] = 99
HW3[24:25,7] = 99
HW3[18:19,3] = 0
HW3[13:14,9] = 0
HW3[9:10,6] = 0
HW3[19:20,14] = 1
print(HW3)

In [91]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [94]:
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)